spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.129.224.87:3306/za_blog?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: DarkNess15

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: org.za.blog.entity
